### ISSUE TITLE
Mutually recursive data models are broken w/ newly implemented input types.

### ISSUE THREAD

**Issue by joelgardner** [johanatan/graphql-type-lang-compiler#3] opened 2016-11-23 10:08 UTC
Upgrading to 0.9.23 resulted in non-compilation with error:

```
Error: Can only create List of a GraphQLType but got: null.
```

To reproduce in the `examples/albums.js`, add `albums: [Album]` to the `Label` type at https://github.com/johanatan/graphql-type-lang-compiler/blob/master/examples/albums.js#L33

**Comment by johanatan** [comment] 2016-11-28 19:31
I just tested with a List type to a primitive datatype [i.e.,  String] (rather than a mutually recursive one) and that works fine in 0.9.23.

It seems the problem is rather that the previously implemented input type fix (https://github.com/johanatan/graphql-type-lang-compiler/commit/dac9098ad9558d325151b1836f6d53a1b1824cdd) has broken mutually recursive data models and after a little bit of investigation I've determined the fix for this is non-trivial/expensive.

For now, I recommend avoiding mutually-recursive data models.

**Closed as completed** 2016-12-01 21:28 UTC
